"""members.credits + sessions.completed + statuses

Revision ID: 90002c87e9f6
Revises: 
Create Date: 2025-08-09 16:17:37.488508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90002c87e9f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_sessions_completed'), ['completed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_completed'))
        batch_op.drop_column('completed')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
